spring: 
  profiles:
     active: redis,postgrel,dev
  thymeleaf:
    cache: false
    
    
server:
  port: 8888

sino:
  responseControllerAdvice:
      enabled: false
  mybatisConfigurationCustomizer:
      enabled: false
  paginationInterceptor: 
      enabled: false     


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG


  
