spring: 
  profiles:
     active: redis,postgrel,dev
  thymeleaf:
    cache: false
    
    
server:
  port: 8888

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG


  
